version: '3'

services:
    nginx_service:
        image: nginx/developement-nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/html:/usr/share/nginx/html:ro
            - ./nginx/sites-available:/etc/nginx/sites-available:ro
            - ./nginx/sites-available:/etc/nginx/sites-enabled:ro
            - ./log-location:/var/log/nginx/
            - ./porject-root:/usr/share/vm-file-loaction
        networks:
            - sample
        restart: always
        container_name: nginx-sample
        hostname: dev.testDemo.com

    phpfpm_service:
        image: php/developement-phpfpm
        ports:
            - "9000:9000"
        volumes:
            - ./porject-root:/usr/share/vm-file-loaction
        networks:
            - sample
        restart: always
        working_dir: /vm-file-loaction
        # command php artisan queue:listen
        container_name: php-fpm-sample
        extra_hosts:

    php_websocket_service:
        image: php/developement-phpfpm
        ports:
            - "8008:8008"
        volumes:
            - ./porject-root:/usr/share/vm-file-loaction
        networks:
            - sample
        restart: always
        working_dir: /vm-file-loaction
        # command php artisan websocket-service:start websocket-server
        container_name: php-websocket-sample

    mysql_service:
        image: mysql/developement-mysql
        ports:
            - "3306:3306"
        networks:
            - sample
        volumes:
            - simple-db-data:/var/lib/mysql
        restart: always
        container_name: mysql-simple
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_USER: peanut
            MYSQL_PASSWORD: john1994
            TZ: Asia/Taipei

    redis_service:
        image: redis/developement-redis
        ports:
            - "6379:6379"
        networks:
            - simple
        restart: always
        container_name: redis-simple
        environment:
            REDIS_PASSWORD: 123456

networks:
    simple:

volumes:
    simple-db-data:
        external: true
